name: Check token logo URIs

on:
  push:
    paths:
      - 'src/coins.ts'
jobs:
  test:
    runs-on: runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install modules
        run: yarn
      - name: Try to fetch tokens
        run: yarn test coins.logo.test.ts
